language: objective-c

osx_image: xcode10

before_install:
  - gem install cocoapods
  - gem install xcpretty
  - pod repo update

script:
  - pod lib lint --use-libraries --allow-warnings
  - make test